---
- hosts: all
  tasks:
    - name: message
      debug: msg="Container - {{ inventory_hostname }} running {{ ansible_distribution }}"
    - name: install
      package: name=postgresql state=installed
