---
- name: install
  package: name={{ item }} state=present
  with_items: "{{ nfs_packages }}"

- name: exports
  template:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
