galaxy_info:
  role_name: docker_postgres
  author: Pavlo Bashynskyi
  description: Manage and run the PostgreSQL docker container.
  license: MIT
  company: —
  min_ansible_version: 2.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: MacOSX
    versions:
    - all
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: GenericUNIX
    versions:
    - any
  - name: ArchLinux
    versions:
    - all
  - name: FreeBSD
    versions:
    - all
  cloud_platforms: []
  galaxy_tags:
  - postgresql
  - postgres
  - database
  - docker

dependencies: []
