---
# tasks for k8
- name: "Changing driver in docker"
  copy:
    content: |
            {
               "exec-opts": ["native.cgroupdriver=systemd"]
            }
    dest: /etc/docker/daemon.json
  register: z

- name: "Restarting docker"
  service:
    name: docker
    state: restarted 
  when: z.changed == true

- name: "Updating config file"
  copy: 
    dest: /etc/sysctl.d/k8s.conf
    content: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
- name: "Changing parameters for kernel"
  command: "sysctl --system"

- name: "Create file"
  file:
    path: /root/token
    state: touch
    mode: '0644'
    
- copy:
    src: /tmp/token
    dest: /root/token
    
- name: "Join to cluster"
  shell: "bash /root/token"
  ignore_errors: yes
